# Generated by Django 3.0.2 on 2020-06-22 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacollection',
            name='end_date_time',
        ),
        migrations.RemoveField(
            model_name='datacollection',
            name='start_date_time',
        ),
        migrations.AddField(
            model_name='datacollection',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='datacollection',
            name='first_perception',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='datacollection',
            name='last_perception',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='datacollection',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='datacollection',
            name='stop_time',
            field=models.TimeField(null=True),
        ),
    ]
