# Generated by Django 3.0.2 on 2020-08-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='irsupport',
            name='energy',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
