# Generated by Django 3.0.2 on 2020-06-22 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0002_auto_20200622_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacollection',
            name='date',
        ),
        migrations.RemoveField(
            model_name='datacollection',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='datacollection',
            name='stop_time',
        ),
    ]
