# Generated by Django 3.0.2 on 2020-08-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0002_irsupport_energy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boostangledetail',
            name='boost_symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bracketedc',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='c',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gasgiant',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='irsupport',
            name='sym',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='moon',
            name='sym',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='multiplesquare',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='opposition',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sextile',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trine',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
