# Generated by Django 3.0.2 on 2020-08-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0003_auto_20200807_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplesquare',
            name='body1',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
