# Generated by Django 3.0.2 on 2020-06-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0004_auto_20200622_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollection',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
