# Generated by Django 3.0.2 on 2020-08-27 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0004_multiplesquare_body1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdata',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basic_data', to='collectdata.UserDetail'),
        ),
    ]
