# Generated by Django 3.0.2 on 2020-06-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0005_datacollection_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollection',
            name='total_drawing',
            field=models.IntegerField(null=True),
        ),
    ]
