# Generated by Django 3.0.2 on 2020-08-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0006_auto_20200827_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='boostangle',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='boostangledetail',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bracketed',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bracketedc',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='c',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='gasgiant',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irsupport',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='moon',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='multiplesquare',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='opposition',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sextile',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='trine',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
