# Generated by Django 3.0.2 on 2020-06-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0006_datacollection_total_drawing'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollection',
            name='boost_angle',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=30, null=True),
        ),
    ]
