# Generated by Django 3.0.2 on 2020-06-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0007_datacollection_boost_angle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacollection',
            name='boost_angle',
        ),
        migrations.RemoveField(
            model_name='datacollection',
            name='date',
        ),
        migrations.RemoveField(
            model_name='datacollection',
            name='first_perception',
        ),
        migrations.RemoveField(
            model_name='datacollection',
            name='last_perception',
        ),
        migrations.RemoveField(
            model_name='datacollection',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='datacollection',
            name='stop_time',
        ),
        migrations.RemoveField(
            model_name='datacollection',
            name='total_drawing',
        ),
    ]
