# Generated by Django 3.0.2 on 2020-06-25 10:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0008_auto_20200624_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basicdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('stop_time', models.TimeField(null=True)),
                ('total_time', models.TimeField(null=True)),
                ('first_perception', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_perception', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_drawing', models.IntegerField(null=True)),
                ('correct', models.CharField(max_length=30, null=True)),
                ('displaced', models.CharField(max_length=30, null=True)),
                ('meld', models.CharField(max_length=30, null=True)),
                ('type', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoostAngle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=10, null=True)),
                ('boost_angle', models.CharField(max_length=10, null=True)),
                ('degree', models.CharField(max_length=10, null=True)),
                ('degree_type', models.CharField(max_length=10, null=True)),
                ('energy', models.CharField(max_length=10, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collectdata.Basicdata')),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_condition', models.CharField(max_length=10, null=True)),
                ('second_condition', models.CharField(max_length=10, null=True)),
                ('degree', models.CharField(max_length=10, null=True)),
                ('degree_type', models.CharField(max_length=10, null=True)),
                ('bracketed', models.CharField(max_length=10, null=True)),
                ('energy', models.CharField(max_length=10, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collectdata.Basicdata')),
            ],
        ),
        migrations.CreateModel(
            name='Gasgiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas', models.CharField(max_length=10, null=True)),
                ('degree', models.CharField(max_length=10, null=True)),
                ('degree_type', models.CharField(max_length=10, null=True)),
                ('energy', models.CharField(max_length=10, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collectdata.Basicdata')),
            ],
        ),
        migrations.CreateModel(
            name='Irsupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=10, null=True)),
                ('degree', models.CharField(max_length=10, null=True)),
                ('degree_type', models.CharField(max_length=10, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collectdata.Basicdata')),
            ],
        ),
        migrations.DeleteModel(
            name='DataCollection',
        ),
    ]
