# Generated by Django 3.0.2 on 2020-06-25 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0009_auto_20200625_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicdata',
            name='total_time',
        ),
        migrations.AlterField(
            model_name='basicdata',
            name='first_perception',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='basicdata',
            name='last_perception',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
