# Generated by Django 3.0.2 on 2020-06-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0010_auto_20200625_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicdata',
            name='total_time',
            field=models.TimeField(null=True),
        ),
    ]
