# Generated by Django 3.0.2 on 2020-06-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0011_basicdata_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boostangle',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='gasgiant',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='irsupport',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
