# Generated by Django 3.0.2 on 2020-06-26 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0012_auto_20200626_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='total_condition',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='basicdata',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='basicdata',
            name='type',
            field=models.CharField(choices=[('None', 'None'), ('SEW', 'SEW'), ('MEW', 'MEW')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='boostangle',
            name='degree',
            field=models.CharField(choices=[('0', '0'), ('60', '60'), ('90', '90'), ('120', '120'), ('180', '180')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='boostangle',
            name='degree_type',
            field=models.CharField(choices=[('None', 'None'), ('Applying', 'Applying'), ('Seperating', 'Seperating')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='boostangle',
            name='energy',
            field=models.CharField(choices=[('None', 'None'), ('Positive', 'Positive'), ('Negative', 'Negative')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='boostangle',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collectdata.Basicdata'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='bracketed',
            field=models.CharField(choices=[('None', 'None'), ('YES', 'NO'), ('YES', 'NO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='degree',
            field=models.CharField(choices=[('0', '0'), ('60', '60'), ('90', '90'), ('120', '120'), ('180', '180')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='degree_type',
            field=models.CharField(choices=[('None', 'None'), ('Applying', 'Applying'), ('Seperating', 'Seperating')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='energy',
            field=models.CharField(choices=[('None', 'None'), ('Positive', 'Positive'), ('Negative', 'Negative')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='first_condition',
            field=models.CharField(choices=[('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('C7', 'C7'), ('C8', 'C8'), ('C9', 'C9'), ('C10', 'C10'), ('C11', 'C11')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collectdata.Basicdata'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='second_condition',
            field=models.CharField(choices=[('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('C7', 'C7'), ('C8', 'C8'), ('C9', 'C9'), ('C10', 'C10'), ('C11', 'C11')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gasgiant',
            name='degree',
            field=models.CharField(choices=[('0', '0'), ('60', '60'), ('90', '90'), ('120', '120'), ('180', '180')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gasgiant',
            name='degree_type',
            field=models.CharField(choices=[('None', 'None'), ('Applying', 'Applying'), ('Seperating', 'Seperating')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gasgiant',
            name='energy',
            field=models.CharField(choices=[('None', 'None'), ('Positive', 'Positive'), ('Negative', 'Negative')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gasgiant',
            name='gas',
            field=models.CharField(choices=[('C1', 'C1'), ('C6B', 'C6B'), ('C7', 'C7')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gasgiant',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collectdata.Basicdata'),
        ),
        migrations.AlterField(
            model_name='irsupport',
            name='body',
            field=models.CharField(choices=[('C1', 'C1'), ('C2B', 'C2B'), ('C3B', 'C3B'), ('C4', 'C4'), ('C5', 'C5'), ('C6B', 'C6B')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='irsupport',
            name='degree',
            field=models.CharField(choices=[('0', '0'), ('60', '60'), ('90', '90'), ('120', '120'), ('180', '180')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='irsupport',
            name='degree_type',
            field=models.CharField(choices=[('None', 'None'), ('Applying', 'Applying'), ('Seperating', 'Seperating')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='irsupport',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collectdata.Basicdata'),
        ),
    ]
