# Generated by Django 3.0.2 on 2020-06-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0013_auto_20200626_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='bracketed',
            field=models.CharField(choices=[('None', 'None'), ('YES', 'YES'), ('NO', 'NO')], max_length=10, null=True),
        ),
    ]
