# Generated by Django 3.0.2 on 2020-06-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0014_auto_20200626_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boostangle',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='gasgiant',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='irsupport',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
