# Generated by Django 3.0.2 on 2020-06-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0015_auto_20200626_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='bracketed',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='second_condition',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='total_condition',
        ),
        migrations.AddField(
            model_name='basicdata',
            name='bracketed',
            field=models.CharField(choices=[('None', 'None'), ('YES', 'YES'), ('NO', 'NO')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='irsupport',
            name='sym',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=10, null=True),
        ),
    ]
