# Generated by Django 3.0.2 on 2020-07-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0016_auto_20200629_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='BracketedC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('body', models.CharField(max_length=30, null=True)),
                ('degree90', models.IntegerField(null=True)),
                ('degree_applying90', models.CharField(max_length=10, null=True)),
                ('degree_separating90', models.CharField(max_length=10, null=True)),
                ('degree180', models.IntegerField(null=True)),
                ('degree_applying180', models.CharField(max_length=10, null=True)),
                ('degree_separating180', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('body', models.CharField(max_length=30, null=True)),
                ('degree_applying', models.CharField(max_length=10, null=True)),
                ('degree_separating', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleSquare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('body', models.CharField(max_length=30, null=True)),
                ('degree', models.IntegerField(null=True)),
                ('degree_applying', models.CharField(max_length=10, null=True)),
                ('degree_separating', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('body1', models.CharField(max_length=30, null=True)),
                ('angle', models.CharField(max_length=30, null=True)),
                ('body2', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sextile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('degree', models.IntegerField(null=True)),
                ('body', models.CharField(max_length=30, null=True)),
                ('degree_applying', models.CharField(max_length=10, null=True)),
                ('degree_separating', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('degree', models.IntegerField(null=True)),
                ('body', models.CharField(max_length=30, null=True)),
                ('degree_applying', models.CharField(max_length=10, null=True)),
                ('degree_separating', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='basicdata',
            name='bracketedIROR',
            field=models.CharField(choices=[('IR', 'IR'), ('IR', 'OR'), ('OR', 'IR')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='basicdata',
            name='giantsquare',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='basicdata',
            name='house',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='basicdata',
            name='multiple_opposition',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='basicdata',
            name='opp',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='basicdata',
            name='bracketed',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='basicdata',
            name='type',
            field=models.CharField(choices=[('SEW', 'SEW'), ('MEW', 'MEW')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='boostangle',
            name='degree_type',
            field=models.CharField(choices=[('Applying', 'Applying'), ('Seperating', 'Seperating')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='boostangle',
            name='energy',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='degree_type',
            field=models.CharField(choices=[('Applying', 'Applying'), ('Seperating', 'Seperating')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='energy',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=10, null=True),
        ),
    ]
