# Generated by Django 3.0.2 on 2020-07-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0017_auto_20200716_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicdata',
            old_name='meld',
            new_name='correct_meld',
        ),
        migrations.AddField(
            model_name='basicdata',
            name='incorect_meld',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='basicdata',
            name='total_meld',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gasgiant',
            name='body',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='first_condition',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gasgiant',
            name='degree_type',
            field=models.CharField(choices=[('Applying', 'Applying'), ('Seperating', 'Seperating')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gasgiant',
            name='energy',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=10, null=True),
        ),
    ]
