# Generated by Django 3.0.2 on 2020-07-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0018_auto_20200717_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdata',
            name='bracketed',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='basicdata',
            name='bracketedIROR',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='basicdata',
            name='giantsquare',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='basicdata',
            name='multiple_opposition',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='basicdata',
            name='opp',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='basicdata',
            name='type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='boostangle',
            name='degree',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='boostangle',
            name='degree_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='boostangle',
            name='energy',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='degree',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='degree_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='energy',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gasgiant',
            name='degree',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gasgiant',
            name='degree_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gasgiant',
            name='energy',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gasgiant',
            name='gas',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='irsupport',
            name='body',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='irsupport',
            name='degree',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='irsupport',
            name='degree_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='irsupport',
            name='sym',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
