# Generated by Django 3.0.2 on 2020-08-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0020_auto_20200717_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracketed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bracket', models.CharField(max_length=30, null=True)),
                ('body', models.CharField(max_length=10, null=True)),
                ('degree_type', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='boostangle',
            old_name='body',
            new_name='body0',
        ),
        migrations.RenameField(
            model_name='boostangle',
            old_name='boost_angle',
            new_name='body1',
        ),
        migrations.RenameField(
            model_name='boostangle',
            old_name='degree',
            new_name='body10',
        ),
        migrations.RenameField(
            model_name='boostangle',
            old_name='degree_type',
            new_name='body11',
        ),
        migrations.RenameField(
            model_name='boostangle',
            old_name='energy',
            new_name='body12',
        ),
        migrations.RenameField(
            model_name='bracketedc',
            old_name='degree_applying180',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='bracketedc',
            old_name='degree_applying90',
            new_name='degree_type',
        ),
        migrations.RenameField(
            model_name='bracketedc',
            old_name='degree180',
            new_name='symbol',
        ),
        migrations.RenameField(
            model_name='c',
            old_name='degree_applying',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='c',
            old_name='degree_separating',
            new_name='degree_type',
        ),
        migrations.RenameField(
            model_name='moon',
            old_name='degree_applying',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='moon',
            old_name='degree_separating',
            new_name='degree_type',
        ),
        migrations.RenameField(
            model_name='multiplesquare',
            old_name='degree_applying',
            new_name='degree_type',
        ),
        migrations.RenameField(
            model_name='opposition',
            old_name='angle',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='sextile',
            old_name='degree_applying',
            new_name='degree_type',
        ),
        migrations.RenameField(
            model_name='trine',
            old_name='degree_applying',
            new_name='degree_type',
        ),
        migrations.RemoveField(
            model_name='basicdata',
            name='bracketed',
        ),
        migrations.RemoveField(
            model_name='bracketedc',
            name='degree90',
        ),
        migrations.RemoveField(
            model_name='bracketedc',
            name='degree_separating180',
        ),
        migrations.RemoveField(
            model_name='bracketedc',
            name='degree_separating90',
        ),
        migrations.RemoveField(
            model_name='multiplesquare',
            name='degree_separating',
        ),
        migrations.RemoveField(
            model_name='sextile',
            name='degree_separating',
        ),
        migrations.RemoveField(
            model_name='trine',
            name='degree_separating',
        ),
        migrations.AddField(
            model_name='boostangle',
            name='body13',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='boostangle',
            name='body2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='boostangle',
            name='body3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='boostangle',
            name='boost_angle0',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='boostangle',
            name='boost_angle1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='boostangle',
            name='boost_angle2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='boostangle',
            name='boost_angle3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='boostangle',
            name='degree0',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='boostangle',
            name='degree1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='boostangle',
            name='degree2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='boostangle',
            name='degree3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='boostangle',
            name='degree_type0',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='boostangle',
            name='degree_type1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='boostangle',
            name='degree_type2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='boostangle',
            name='degree_type3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='boostangle',
            name='energy0',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='boostangle',
            name='energy1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='boostangle',
            name='energy2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='boostangle',
            name='energy3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='c',
            name='body1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='c',
            name='symbol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='conditionbody',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gasgiant',
            name='symbol',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='multiplesquare',
            name='symbol',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='opposition',
            name='degree_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='opposition',
            name='symbol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sextile',
            name='body1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sextile',
            name='symbol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trine',
            name='body1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trine',
            name='symbol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='multiplesquare',
            name='degree',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sextile',
            name='degree',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trine',
            name='degree',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
