# Generated by Django 3.0.2 on 2020-08-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0021_auto_20200803_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracketed',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
