# Generated by Django 3.0.2 on 2020-08-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0022_bracketed_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boostangle',
            old_name='body0',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='boostangle',
            old_name='body10',
            new_name='boost_angle',
        ),
        migrations.RenameField(
            model_name='boostangle',
            old_name='body11',
            new_name='boostanglebody',
        ),
        migrations.RenameField(
            model_name='boostangle',
            old_name='body12',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='boostangle',
            old_name='body13',
            new_name='degree_type',
        ),
        migrations.RenameField(
            model_name='boostangle',
            old_name='body2',
            new_name='energy',
        ),
        migrations.RemoveField(
            model_name='boostangle',
            name='body3',
        ),
        migrations.RemoveField(
            model_name='boostangle',
            name='boost_angle0',
        ),
        migrations.RemoveField(
            model_name='boostangle',
            name='boost_angle1',
        ),
        migrations.RemoveField(
            model_name='boostangle',
            name='boost_angle2',
        ),
        migrations.RemoveField(
            model_name='boostangle',
            name='boost_angle3',
        ),
        migrations.RemoveField(
            model_name='boostangle',
            name='degree0',
        ),
        migrations.RemoveField(
            model_name='boostangle',
            name='degree1',
        ),
        migrations.RemoveField(
            model_name='boostangle',
            name='degree2',
        ),
        migrations.RemoveField(
            model_name='boostangle',
            name='degree3',
        ),
        migrations.RemoveField(
            model_name='boostangle',
            name='degree_type0',
        ),
        migrations.RemoveField(
            model_name='boostangle',
            name='degree_type1',
        ),
        migrations.RemoveField(
            model_name='boostangle',
            name='degree_type2',
        ),
        migrations.RemoveField(
            model_name='boostangle',
            name='degree_type3',
        ),
        migrations.RemoveField(
            model_name='boostangle',
            name='energy0',
        ),
        migrations.RemoveField(
            model_name='boostangle',
            name='energy1',
        ),
        migrations.RemoveField(
            model_name='boostangle',
            name='energy2',
        ),
        migrations.RemoveField(
            model_name='boostangle',
            name='energy3',
        ),
        migrations.AlterField(
            model_name='multiplesquare',
            name='degree',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
