# Generated by Django 3.0.2 on 2020-08-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0025_auto_20200803_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracketedc',
            name='body1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bracketed',
            name='body',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
