# Generated by Django 3.0.2 on 2020-08-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0026_auto_20200803_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoostAngleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('boostanglebody', models.CharField(max_length=10, null=True)),
                ('body', models.CharField(max_length=10, null=True)),
                ('boost_symbol', models.IntegerField(null=True)),
                ('body1', models.CharField(max_length=10, null=True)),
                ('degree', models.CharField(max_length=10, null=True)),
                ('degree_type', models.CharField(max_length=10, null=True)),
                ('energy', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='boostangle',
            name='body1',
        ),
        migrations.RemoveField(
            model_name='boostangle',
            name='boost_symbol',
        ),
        migrations.RemoveField(
            model_name='boostangle',
            name='energy',
        ),
    ]
