# Generated by Django 3.0.2 on 2020-08-05 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0027_auto_20200804_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='basicdata',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collectdata.UserDetail'),
        ),
        migrations.AlterField(
            model_name='boostangle',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collectdata.UserDetail'),
        ),
        migrations.AlterField(
            model_name='boostangledetail',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collectdata.UserDetail'),
        ),
        migrations.AlterField(
            model_name='bracketed',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collectdata.UserDetail'),
        ),
        migrations.AlterField(
            model_name='bracketedc',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collectdata.UserDetail'),
        ),
        migrations.AlterField(
            model_name='c',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collectdata.UserDetail'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collectdata.UserDetail'),
        ),
        migrations.AlterField(
            model_name='gasgiant',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collectdata.UserDetail'),
        ),
        migrations.AlterField(
            model_name='irsupport',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collectdata.UserDetail'),
        ),
        migrations.AlterField(
            model_name='moon',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collectdata.UserDetail'),
        ),
        migrations.AlterField(
            model_name='multiplesquare',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collectdata.UserDetail'),
        ),
        migrations.AlterField(
            model_name='opposition',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collectdata.UserDetail'),
        ),
        migrations.AlterField(
            model_name='sextile',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collectdata.UserDetail'),
        ),
        migrations.AlterField(
            model_name='trine',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collectdata.UserDetail'),
        ),
    ]
